CC=gcc
CFLAGS= # l-lm
SOURCES=GaussianElimination.c Libtest.c Movement.c PeriodicFractionSolver.c StringEvaluation.c TextAssignments.c Utils.c

all: TooManyEquations

TooManyEquations: $(SOURCES)
	$(CC) -o TooManyEquations $(SOURCES) $(CFLAGS)